config/routes.rb
Rails.application.routes.draw do
  
  #get 'payment_select/select_plan'

  get '/select_plan' => 'payment_select#select_plan', as: :select_plan
  #get 'payment_select/select_monthly_subscription'
  get '/select_monthly_subscription' => 'payment_select#select_monthly_subscription', as: :select_monthly_subscription
  get 'select_movies/index'

  # Order is important
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users
  ActiveAdmin.routes(self)  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # You can have the root of your site routed with "root"
	
	#root :to => "statics#index"
	#Example of regular route:
	#get 'about' => 'pages#about', as: 'about'
	#get '/about' => 'statics#about', :as => :about
	get 'about' => 'about#index', as: 'about'
	get 'settings/index'
	get 'movies/index_search' => 'movies#index_search'
	#Example resource route
	resources :movies do
		resources :comments
		resources :reviews
	end
	
  resources :settings
  resources :charges
	resources :select_movies, only: :index
	
	root 'movies#index', as: 'home'
	#added for method root_path (search)
	root :to => "movies#index"

	require 'sidekiq/web'
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

end
	

app/views/partials/_footer.html.erb
<section id="footer" style="background-color:#292b34;">
    <div class="container">
    <center style="color:#fff;">
    <div class="container">
        <div class="well well-sm main-footer"  style="background-color:#292b34; border:0px">
            <div class="row">
                <div class="col-md-12">
                    <div class="row">
                        <div class="col-md-4">
                            <img class="img-responsive" src="http://res.cloudinary.com/lawless/image/upload/c_scale,h_150/v1496303248/mini_lion_fliyjw.png" alt="lion-foto">
                        </div><!--end .col-md-4-->
                        <div class="col-md-4 contact-email">                            
                            <h4 id="copy">Designed with <i id="heart" class="glyphicon glyphicon-heart"></i> by <span id="tag-name">L4w3sS</span> for developers</h3>
                        </div><!--end .col-md-4 .contact-email-->
                        <div class="col-md-4">
                            <div class="row contact row-first">
                                <h1 id="sos">Social Media</h1>
                                <ul class="footer-social">
                                  <i href="#" class="fa fa-linkedin social-icon linked-in" aria-hidden="true"></i>
                                  <i href="#" class="fa fa-facebook social-icon facebook" aria-hidden="true"></i>
                                  <i href="#" class="fa fa-twitter social-icon twitter" aria-hidden="true"></i>
                                  <i href="#" class="fa fa-google-plus social-icon google" aria-hidden="true"></i>
                                </ul>
                                <h3>
                                <a id="sos2" href="#">L4wLesS@emailreplay.com</a></h3>
                            </div><!--end .row .contact-->
                        </div><!--end .col-md-6-->
                    </div><!--end .row-->
                </div><!--end .col-md-12-->
            </div><!--end .row-->
        </div><!--end .well .well-sm .main-footer-->
    </div><!--end .container-->
    </center>
  </div><!--end .container-->
</section>

app/views/partials/_header.html.erb
<style>
  .navbar-brand{
    color: #374140 !important;
  }
</style>
<nav class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#"><b>MoviesL4wL3sS</b></a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "About", about_path %></li>            
          </ul>
          <ul class="nav navbar-nav navbar-right">
              <!-- <li><%= render 'partials/search_dropdown' %></li> -->
            <% if user_signed_in? %>
              <li><%= link_to "Create Movie", new_movie_path %></li>
              <li><%= link_to "Edit Account", edit_user_registration_path %></li>
              <!-- settings simbol -->
              <%= link_to '<li id ="nav_log_out" class="fa fa-home fa-3 hidden-xs"></li>'.html_safe, settings_path %>
              <%= link_to '<li class=" visible-xs">Profile</li>'.html_safe, settings_path %>
              <span id="nav_user"><b><%= current_user.username %></b></span>
              <!-- log_out simbol -->  
              <%= link_to '<li id ="nav_log_out" class="fa fa-sign-out fa-3 hidden-xs"></li>'.html_safe, destroy_user_session_path, method: :delete %>
              <%= link_to '<li class=" visible-xs">Log_Out</li>'.html_safe, destroy_user_session_path, method: :delete %>


            <% else %>

              <li><%= link_to "Sign In", new_user_session_path %></li>
              <li><%= link_to "Sign Up", new_user_registration_path %></li>
            
            <% end %>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
</nav>

app/views/partials/_row.html.erb
<th>
	<% if movie.stars < 5 %>
		<img src="http://res.cloudinary.com/lawless/image/upload/c_scale,h_25/v1496319628/inset_coin_kyvs7l.png" alt="insert_coin">
	<% elsif movie.stars <= 6 %>
			<img src="http://res.cloudinary.com/lawless/image/upload/c_scale,h_25/v1496319629/bornce_coin_vthk3p.png" alt="insert_coin">
	<% elsif movie.stars <= 8 %>
			<img src="http://res.cloudinary.com/lawless/image/upload/c_scale,h_25/v1496319629/silver_coin_oq6chf.png" alt="insert_coin">
	<% elsif movie.stars <= 10 %>
			<img src="http://res.cloudinary.com/lawless/image/upload/c_scale,h_25/v1496319629/gold_coin_md3n8f.png" alt="insert_coin">
	<% end %>
</th>

app/views/partials/_search_dropdown.html.erb
<style type="text/css">
  
</style>
<form class="navbar-form navbar-search" role="search">
  <div class="input-group">
    <input type="text" class="form-control" placeholder="Search">    
    <div class="input-group-btn">            
      <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
        <span class="caret"></span>
      </button>
      <ul class="dropdown-menu pull-right" role="menu">
        <li>
          <a href="#">
            <span class="label-icon">Search By Title</span>
          </a>
        </li>
        <li>
          <a href="#">
          <span class="label-icon">Search By Year</span>
          </a>
        </li>
      </ul>
    </div>
  </div>  
</form>   

app/views/partials/_searcher.html.erb
<% if params[:controller] == "select_movies"%>
	<div class="container text-center hidden-xs hidden-sm" id="div-sercher">
		<div class="form-inline pull-left">
			<%= form_tag(select_movies_path, :method => "get", id: "search-form") do %>
	    		<%= text_field_tag :search, params[:search], placeholder: "Search Movies", class: '	form-control' %>
	    		<%= submit_tag t('search.submit'), class: 'btn btn-default' %>
			<% end %>
		</div>	
		<div class="form-inline pull-left">
			<%= form_tag(select_movies_path, :method => "get", id: "search-form") do %>
			    <%= text_field_tag :search_director, params[:search_director], placeholder: "Search Director", class: 'form-control' %>
			    <%= submit_tag t('search.submit'), class: 'btn btn-default' %>
			<% end %>
		</div>	
		<div class="form-inline pull-left">		
			<%= form_tag(select_movies_path, :method => "get", id: "search-form") do %>
				<%= text_field_tag :search_year, params[:search_year], placeholder: "Search Year", class: 'form-control' %>
				<%= submit_tag t('search.submit'), class: 'btn btn-default' %>
			<% end %>
		</div>
		<div class="form-inline pull-left">
			<%= form_tag(select_movies_path, :method => "get", id: "genre") do %>
				<%= select_tag :search_genre, ("<option> Select Genre</option><br><option>ACTION</option><option>ADVENTURE</option><option>COMEDY</option><option>CRIME</option><option>DRAMA</option><option>HISTORICAL</option><option>HORROR</option><option>MUSICALS</option><option>SIENCE-FICTION</option><option>WAR</option><option>WESTERNS</option>").html_safe, class: 'btn btn-default', :onchange => "this.form.submit()"%>
			<% end %>
		</div>		
	</div>
	<div class="container text-center visible-xs visible-sm" id="div-sercher">
		<div class="form-inline ">
			<%= form_tag(select_movies_path, :method => "get", id: "search-form") do %>
	    		<%= text_field_tag :search, params[:search], placeholder: "Search Movies", class: '	form-control-sm' %>
	    		<%= submit_tag t('search.submit'), class: 'btn-sm btn-default' %>
			<% end %>
		</div>	
		<div class="form-inline ">
			<%= form_tag(select_movies_path, :method => "get", id: "search-form") do %>
			    <%= text_field_tag :search_director, params[:search_director], placeholder: "Search Director", class: 'form-control-sm' %>
			    <%= submit_tag t('search.submit'), class: 'btn-sm btn-default' %>
			<% end %>
		</div>	
		<div class="form-inline ">		
			<%= form_tag(select_movies_path, :method => "get", id: "search-form") do %>
				<%= text_field_tag :search_year, params[:search_year], placeholder: "Search Year", class: 'form-control-sm' %>
				<%= submit_tag t('search.submit'), class: 'btn-sm btn-defaultl' %>
			<% end %>
		</div>
		<div class="form-inline" id="genre">
			<%= form_tag(select_movies_path, :method => "get", id: "search-form") do %>
				<%= select_tag :search_genre, ("<option> Select Genre</option><br><option>ACTION</option><option>ADVENTURE</option><option>COMEDY</option><option>CRIME</option><option>DRAMA</option><option>HISTORICAL</option><option>HORROR</option><option>MUSICALS</option><option>SIENCE-FICTION</option><option>WAR</option><option>WESTERNS</option>").html_safe, class: 'btn-sm btn-default', :onchange => "this.form.submit()"%>
			<% end %>
		</div>		
	</div>
<% else %>
	<div class="container text-center hidden-xs hidden-sm" id="div-sercher">
		<div class="form-inline pull-left">
			<%= form_tag(root_path, :method => "get", id: "search-form") do %>
	    		<%= text_field_tag :search, params[:search], placeholder: "Search Movies", class: '	form-control' %>
	    		<%= submit_tag t('search.submit'), class: 'btn btn-default' %>
			<% end %>
		</div>	
		<div class="form-inline pull-left">
			<%= form_tag(root_path, :method => "get", id: "search-form") do %>
			    <%= text_field_tag :search_director, params[:search_director], placeholder: "Search Director", class: 'form-control' %>
			    <%= submit_tag t('search.submit'), class: 'btn btn-default' %>
			<% end %>
		</div>	
		<div class="form-inline pull-left">		
			<%= form_tag(root_path, :method => "get", id: "search-form") do %>
				<%= text_field_tag :search_year, params[:search_year], placeholder: "Search Year", class: 'form-control' %>
				<%= submit_tag t('search.submit'), class: 'btn btn-default' %>
			<% end %>
		</div>
		<div class="form-inline pull-left">
			<%= form_tag(root_path, :method => "get", id: "genre") do %>
				<%= select_tag :search_genre, ("<option> Select Genre</option><br><option>ACTION</option><option>ADVENTURE</option><option>COMEDY</option><option>CRIME</option><option>DRAMA</option><option>HISTORICAL</option><option>HORROR</option><option>MUSICALS</option><option>SIENCE-FICTION</option><option>WAR</option><option>WESTERNS</option>").html_safe, class: 'btn btn-default', :onchange => "this.form.submit()"%>
			<% end %>
		</div>		
	</div>
	<div class="container text-center visible-xs visible-sm" id="div-sercher">
		<div class="form-inline ">
			<%= form_tag(root_path, :method => "get", id: "search-form") do %>
	    		<%= text_field_tag :search, params[:search], placeholder: "Search Movies", class: '	form-control-sm' %>
	    		<%= submit_tag t('search.submit'), class: 'btn-sm btn-default' %>
			<% end %>
		</div>	
		<div class="form-inline ">
			<%= form_tag(root_path, :method => "get", id: "search-form") do %>
			    <%= text_field_tag :search_director, params[:search_director], placeholder: "Search Director", class: 'form-control-sm' %>
			    <%= submit_tag t('search.submit'), class: 'btn-sm btn-default' %>
			<% end %>
		</div>	
		<div class="form-inline ">		
			<%= form_tag(root_path, :method => "get", id: "search-form") do %>
				<%= text_field_tag :search_year, params[:search_year], placeholder: "Search Year", class: 'form-control-sm' %>
				<%= submit_tag t('search.submit'), class: 'btn-sm btn-defaultl' %>
			<% end %>
		</div>
		<div class="form-inline" id="genre">
			<%= form_tag(root_path, :method => "get", id: "search-form") do %>
				<%= select_tag :search_genre, ("<option> Select Genre</option><br><option>ACTION</option><option>ADVENTURE</option><option>COMEDY</option><option>CRIME</option><option>DRAMA</option><option>HISTORICAL</option><option>HORROR</option><option>MUSICALS</option><option>SIENCE-FICTION</option><option>WAR</option><option>WESTERNS</option>").html_safe, class: 'btn-sm btn-default', :onchange => "this.form.submit()"%>
			<% end %>
		</div>		
	</div>
<% end %>




<br>

app/views/partials/_top_movies.html.erb
<hr>
<div class="row">
	<div class="col-md-6">  
		<table class="table">
	  	<h2>Lastest Movies</h2>                                                                   
		  <div class="table-responsive"> 
		    <thead>
		    	<% @movies.limit(5).order('year desc').each do |movie| %>
		      <tr>		      	
		      	<th>
			      	<% if movie.stars < 5 %>
			      		<img src="http://res.cloudinary.com/lawless/image/upload/c_scale,h_25/v1496319628/inset_coin_kyvs7l.png" alt="insert_coin">
			      	<% elsif movie.stars <= 6 %>
								<img src="http://res.cloudinary.com/lawless/image/upload/c_scale,h_25/v1496319629/bornce_coin_vthk3p.png" alt="insert_coin">
			      	<% elsif movie.stars <= 8 %>
								<img src="http://res.cloudinary.com/lawless/image/upload/c_scale,h_25/v1496319629/silver_coin_oq6chf.png" alt="insert_coin">
			      	<% elsif movie.stars <= 10 %>
								<img src="http://res.cloudinary.com/lawless/image/upload/c_scale,h_25/v1496319629/gold_coin_md3n8f.png" alt="insert_coin">
							<% end %>
		      	</th>
		        <th><%= movie.name%></th>
		        <th>Year: <%= movie.year%></th>        
		        <th><%= link_to "Read More", movie_path(movie)%></th>
		      </tr>
		      <% end %>
		    </thead>
		</table><!-- END table -->
		<br>
		<table class="table">
	  	<h2>TOP 5 Worst Movies All Times</h2>                                                           
		  <div class="table-responsive"> 
		    <thead>
		    	<% @movies.limit(5).order('stars asc').each do |movie| %>
		      <tr>		      	
		      	<th>
			      	<% if movie.stars < 5 %>
			      		<img src="http://res.cloudinary.com/lawless/image/upload/c_scale,h_25/v1496319628/inset_coin_kyvs7l.png" alt="insert_coin">
			      	<% elsif movie.stars <= 6 %>
								<img src="http://res.cloudinary.com/lawless/image/upload/c_scale,h_25/v1496319629/bornce_coin_vthk3p.png" alt="insert_coin">
			      	<% elsif movie.stars <= 8 %>
								<img src="http://res.cloudinary.com/lawless/image/upload/c_scale,h_25/v1496319629/silver_coin_oq6chf.png" alt="insert_coin">
			      	<% elsif movie.stars <= 10 %>
								<img src="http://res.cloudinary.com/lawless/image/upload/c_scale,h_25/v1496319629/gold_coin_md3n8f.png" alt="insert_coin">
							<% end %>
		      	</th>
		        <th><%= movie.name%></th>
		        <th>Year: <%= movie.year%></th>        
		        <th><%= link_to "Read More", movie_path(movie)%></th>
		      </tr>
		      <% end %>
		    </thead>
		</table><!-- END table -->
	</div><!-- END col izq-->
	<div class="col-md-6">  
		<table class="table">
	  	<h2>TOP Best 12 Movies All Times</h2>                                                           
		  <div class="table-responsive"> 
		    <thead>
		    	<% @movies.limit(12).order('stars desc').each do |movie| %>
		      <tr>		      	
		      	<th>
			      	<% if movie.stars < 5 %>
			      		<img src="http://res.cloudinary.com/lawless/image/upload/c_scale,h_25/v1496319628/inset_coin_kyvs7l.png" alt="insert_coin">
			      	<% elsif movie.stars <= 6 %>
								<img src="http://res.cloudinary.com/lawless/image/upload/c_scale,h_25/v1496319629/bornce_coin_vthk3p.png" alt="insert_coin">
			      	<% elsif movie.stars <= 8 %>
								<img src="http://res.cloudinary.com/lawless/image/upload/c_scale,h_25/v1496319629/silver_coin_oq6chf.png" alt="insert_coin">
			      	<% elsif movie.stars <= 10 %>
								<img src="http://res.cloudinary.com/lawless/image/upload/c_scale,h_25/v1496319629/gold_coin_md3n8f.png" alt="insert_coin">
							<% end %>
		      	</th>
		        <th><%= movie.name%></th>
		        <th>Year: <%= movie.year%></th>        
		        <th><%= link_to "Read More", movie_path(movie)%></th>
		      </tr>
		      <% end %>
		    </thead>
		</table><!-- END table -->
	</div><!-- END col der-->
</div><!-- END row -->

app/views/partials/_trailers.html.erb
<style>
  #myCarousel{
    max-width: 900px;
    margin: 0px auto;
  }
  .embed-container {
      position: relative;
      padding-bottom: 56.25%;
      height: 0;      
      overflow: hidden;
  }
  .embed-container iframe {
      position: absolute;
      top:0;
      left: 0;
      width: 100%;      
      height: 100%;
  }
  .container{
    width: 85%;
  }
</style>
<div class="container">  
  <div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>

    <!-- Wrapper for slides trilers -->
    <div class="carousel-inner">
      <div class="item active">
        <div class="embed-container">
        <iframe width="560" height="315" src="https://www.youtube.com/embed/XibzC-e_s5M" frameborder="0" allowfullscreen></iframe>
        </div>        
      </div>
      <div class="item">
        <div class="embed-container">
          <iframe width="560" height="315" src="https://www.youtube.com/embed/H0VW6sg50Pk" frameborder="0" allowfullscreen></iframe>
        </div>
      </div>
      <div class="item">
        <div class="embed-container">
          <iframe width="560" height="315" src="https://www.youtube.com/embed/PjuQ4HCXqeI" frameborder="0" allowfullscreen></iframe>
        </div>
      </div>
    </div>
    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>