config/routes.rb
Rails.application.routes.draw do
  
  #get 'payment_select/select_plan'

  get '/select_plan' => 'payment_select#select_plan', as: :select_plan
  #get 'payment_select/select_monthly_subscription'
  get '/select_monthly_subscription' => 'payment_select#select_monthly_subscription', as: :select_monthly_subscription
  get 'select_movies/index'

  # Order is important
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users
  ActiveAdmin.routes(self)  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # You can have the root of your site routed with "root"
	
	#root :to => "statics#index"
	#Example of regular route:
	#get 'about' => 'pages#about', as: 'about'
	#get '/about' => 'statics#about', :as => :about
	get 'about' => 'about#index', as: 'about'
	get 'settings/index'
	get 'movies/index_search' => 'movies#index_search'
	#Example resource route
	resources :movies do
		resources :comments
		resources :reviews
	end
	
  resources :settings
  resources :charges
	resources :select_movies, only: :index
	
	root 'movies#index', as: 'home'
	#added for method root_path (search)
	root :to => "movies#index"

	require 'sidekiq/web'
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

end
	

app/controllers/payment_select_controller.rb
class PaymentSelectController < ApplicationController
  def select_plan
  	@movie_id = Movie.find(params[:movie])
  end

  def select_monthly_subscription
  end
end

app/helpers/payment_select_helper.rb
module PaymentSelectHelper
end

app/views/payment_select/select_monthly_subscription.html.erb
<h2 class="text-center">Select Monthly Subscription</h2>
<br>
<div class="container30"><!-- Start container30 -->
	<div class="col-xs-4">
		<div class="box1">
			<div class="head">					
				<h1>€ 9,99/mo</h1>
				<h2 style="color: #fff;">Bronze</h2>
			</div>
			<div class="body">
				<p><b>Unlimited</b> Email Addresses</p>
				<p><b>50BG</b> Disk Space</p>
				<p><b>Unlimited</b> MYSQL Databases</p>
				<p><b>Unlimited</b> Domains</p>
				<p><b>Free</b> Billing Systems</p>
				<div class="footer">
					<button calss="btn btn-defautl" type="button">SIGN UP</button>
				</div>
			</div>
		</div><!-- END Box1 -->
	</div><!-- END Colum1 -->
	<div class="col-xs-4">
		<div class="box2">
			<div class="head">					
				<h1>€ 12,99/mo</h1>
				<h2 style="color: #fff;">Silver</h2>
			</div>
			<div class="body">
				<p><b>Unlimited</b> Email Addresses</p>
				<p><b>80BG</b> Disk Space</p>
				<p><b>Unlimited</b> MYSQL Databases</p>
				<p><b>Unlimited</b> Domains</p>
				<p><b>Free</b> Billing Systems</p>
				<div class="footer">
					<button calss="btn btn-defautl" type="button">SIGN UP</button>
				</div>
			</div>
		</div><!-- END Box2 -->
	</div><!-- END Colum2 -->
	<div class="col-xs-4">
		<div class="box3">
			<div class="head">					
				<h1>€ 19,99/mo</h1>
				<h2 style="color: #fff;">Gold</h2>
			</div>
			<div class="body">
				<p><b>Unlimited</b> Email Addresses</p>
				<p><b>120BG</b> Disk Space</p>
				<p><b>Unlimited</b> MYSQL Databases</p>
				<p><b>Unlimited</b> Domains</p>
				<p><b>Free</b> Billing Systems</p>
				<div class="footer">
					<button calss="btn btn-defautl" type="button">SIGN UP</button>
				</div>
			</div>
		</div><!-- END Box3 -->
	</div><!-- END Colum3 -->	
</div><!-- END container30 -->

app/views/payment_select/select_plan.html.erb
<h2 class="text-center">Payment Plan Select</h2>
<br>

	<div class="row">
	<%= link_to new_charge_path(amount: @movie_id.price) do %>
		<div class="col-md-6">
			<div class="container-fluid text-center" id="paymet-cont">
				<img class="img-responsive" src="http://res.cloudinary.com/lawless/image/upload/v1497898486/pop_qsvd5j.png" alt="buy-movie">
				<h2> Buy <%= @movie_id.name %> for: <%= @movie_id.price/100.0 %>€</h2>
			</div>
		</div>		
	<% end %>	
	<%= link_to select_monthly_subscription_path(@movie_id) do %>
		<div class="col-md-6">
			<div class="container-fluid text-center" id="paymet-cont">
				<img class="img-responsive" src="http://res.cloudinary.com/lawless/image/upload/c_scale,w_265/v1497944834/subs_m7ueah.png" alt="sub-img">
				<h2> SUBSCRIBE NOW</h2>
			</div>
		</div>	
	<% end %>	
	</div>	

<!-- 
<%= debug params %>
 -->