config/routes.rb
Rails.application.routes.draw do
  
  #get 'payment_select/select_plan'

  get '/select_plan' => 'payment_select#select_plan', as: :select_plan
  #get 'payment_select/select_monthly_subscription'
  get '/select_monthly_subscription' => 'payment_select#select_monthly_subscription', as: :select_monthly_subscription
  get 'select_movies/index'

  # Order is important
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users
  ActiveAdmin.routes(self)  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # You can have the root of your site routed with "root"
	
	#root :to => "statics#index"
	#Example of regular route:
	#get 'about' => 'pages#about', as: 'about'
	#get '/about' => 'statics#about', :as => :about
	get 'about' => 'about#index', as: 'about'
	get 'settings/index'
	get 'movies/index_search' => 'movies#index_search'
	#Example resource route
	resources :movies do
		resources :comments
		resources :reviews
	end
	
  resources :settings
  resources :charges
	resources :select_movies, only: :index
	
	root 'movies#index', as: 'home'
	#added for method root_path (search)
	root :to => "movies#index"

	require 'sidekiq/web'
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

end
	

app/models/setting.rb
class Setting < ApplicationRecord
  belongs_to :user
  validates :country, presence: {message: :no_country}
  validates :language, presence: {message: :no_language}
  validates :country, length: {minimum: 2, message: :short_country}
  validates :language, length: {minimum: 2, message: :short_language}
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
	before_action :authenticate_user!
	layout "admin"

	def index
	    @setting = current_user.setting
	    
	    @payment = current_user.payments
	    
	    #didn't worck for me T_T?
	    # @payment = []
	    # if current_user.payments.exists?
	    #   @payment = Payments.find_by(user_id: current_user.id)	      
	    # end 

	end

  def show
  	@setting = setting.find(params[:id])
  end	

  def new  	
  	@setting = current_user.build_setting
  	#@setting = Setting.new #hack
  end

  def create
	  @setting = current_user.build_setting(setting_params)
	 
	  if @setting.save
	  		flash[:success] = t('setting.create_success')
			redirect_to settings_path
	  else
	  		#flash[:danger] = t('setting.create_not_success')	#devise errors will do fine
			render :new

	  end
  end

	def edit 
		@setting = Setting.find(params[:id])
	end

	def update
		@setting = Setting.find(params[:id])
		if @setting.update_attributes(setting_params)
			flash[:success] = t('setting.create_success')
   			redirect_to settings_path
		else
			#flash[:danger] = t('setting.create_not_success')  #devise errors will do fine
			render :edit
		end
	end

  def setting_params
  	params.require(:setting).permit(:language, :country)
  end

end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/settings/edit.html.erb
<h2>Edit Settigns</h2>

<% if @setting.errors.any? %>
	<% @setting.errors.full_messages.each do |msg| %>
		<!-- <div class="alert alert-danger"><%= msg %></div> -->
		<p hidden><%= flash[:alert] = msg %></p>
		<%if flash.present?%>
			<div class="row">
			    <div class="col-sm-12 col-md-6 col-md-offset-3" style="padding: 0 0">
			        <%= render partial: "shared/flash_messages_fix", flash: flash %>
			    </div>
			</div>
		<%end%>      	
	<% end %>
<% end %>

<!-- 
<% if @setting.errors.any? %>
	<% @setting.errors.full_messages.each do |msg| %>
		<div class="alert alert-danger"><%= msg %></div>      	
	<% end %>
<% end %>
 -->
 
<%= form_for(@setting) do |f| %>

	<div class="field"> 
		<%= f.label :country %>        	 
    	<%= f.select :country, options_for_country, {}, {:prompt => 'Select One Country',  autofocus: 'true', class: 'form-control'}  %>
	</div> 
	<br>
	<div class="field">
		<%= f.label :language %>        	 
    	<%= f.select :language, options_for_language, {}, {:prompt => 'Select One Country',  autofocus: 'true', class: 'form-control'}  %>
	</div>    
	 
	<div class="field">
		<%= f.submit "Guardar", class:"btn btn-sm btn-danger white pull-right", style:"margin-top: 15px;" %>
	</div>
<% end %>

app/views/settings/index.html.erb
<div class="row container">
	<div class="jumbotron" >
		<h2>Your Favorite Movies on MoviesL4wL3sS</h2>
		<p>Wanna make this page give us some Tip!</p>
		<p><%= link_to "Donate", new_charge_path, class: "btn btn-primary" %></p>
	</div>

	<%if flash.present? %>
		<div class="row">
		    <div class="col-sm-12 col-md-6 col-md-offset-3" style="padding:25px 0">
		        <%= render partial: "shared/flash_messages", flash: flash %>
		    </div>
		</div>
	<%end%>
	
	<div class="col-xs-12 col-md-4">
		<%if !@setting.nil? %>
			<div class="container-set">
				<%= link_to '<li id ="edit-icon" class="nodecor pull-right fa fa-lg fa-pencil-square-o" aria-hidden="true"></li>'.html_safe, edit_setting_path(@setting.id) %>
				<img id="img-user" class="img-responsive" src="http://res.cloudinary.com/lawless/image/upload/bo_5px_solid_rgb:ffffff,c_scale,h_150/v1496690341/default-user_tocuja.png" alt="user-img">
				<p><b><%= current_user.username %></b></p>			 
				<p>Country:&nbsp;<%= @setting.country %></p>
				<p>Language:&nbsp;<%= @setting.language %></p>	 
				<li class="links">Manage Account</li>
				<li class="links">Profile Summary</li>
				<li><%= link_to 'SelectMovies', select_movies_path(@setting.id) %></li>  
			</div>
			
		<%else%>			
			<div class="container-set">
				<%= link_to '<li id ="edit-icon" class="nodecor pull-right fa fa-lg fa-pencil-square-o" aria-hidden="true"></li>'.html_safe, new_setting_path %>	
				<img id="img-user" class="img-responsive" src="http://res.cloudinary.com/lawless/image/upload/bo_5px_solid_rgb:ffffff,c_scale,h_150/v1496690341/default-user_tocuja.png" alt="user-img">
				<p><b><%= current_user.username %></b></p>			 			
			</div>
					
		<%end%>
		<div class="container-set">
			<h2>PORFILE STATS</h2>
			<p><b>Total Profile Views: </b>53</p>
			<p><b>Profile Views Last 7 Days: </b>5</p>
		</div>
		<div class="container-set">
			<h2>ABOUT</h2>
			<p><b>Member Since:</b></p>
			<p><%= current_user.created_at %></p>
			<p><b>Email:</b></p>
			<p><%= current_user.email %></p>
			<p><b>Times Log:</b></p>
			<p><%= current_user.sign_in_count %></p>
			<p><b>Log Since</b></p>
			<p><%= current_user.current_sign_in_at %></p>
		</div>
		<li class="righty">Edit</li>
		<div class="container-set">
			
			<!-- Added payment -->
			<% if !@payment.nil? %>
				<h2>Payments</h2>
				<%@payment.each do |payment|%>
					<p><b>Subscription active:</b></p>
					<p><%= payment.subscription %></p>
					<p><b>Payment Channel:</b></p>
					<p><%= payment.channel %></p>
					<p><b>Payment active:</b></p>
					<p><%= payment.active %></p>
					<p><b>Plan:</b></p>
					<p><%= payment.plan %></p> 
					<p><b>Amount payed:</b></p>
					<p><%= payment.amount %></p>
					<hr>				
				<%end%>
			<%end%>

		</div>
	</div>
			
	<div class="col-xs-12 col-md-8">
		<div class="container-set">
			<h2>WANT-TO-SEE MOVIES</h2>
			<div class="row">
				<div class="col-xs-3">
					<div class="container-item">
						<img id="poster-s" class="img-responsive" src="http://res.cloudinary.com/lawless/image/upload/c_scale,h_200,w_125/v1496691060/galaxy2_ur16fw.png" alt="poster">
						<p>Guard. of the galaxy 2</p>
						<img src="http://res.cloudinary.com/lawless/image/upload/c_scale,h_25/v1496319629/gold_coin_md3n8f.png" alt="insert_coin">
					</div>					
				</div>
				<div class="col-xs-3">
					<div class="container-item">
						<img id="poster-s" class="img-responsive" src="http://res.cloudinary.com/lawless/image/upload/c_scale,h_200,w_125/v1496691060/pirates_last_dsq61h.jpg" alt="poster">
						<p>Praites of crabean 5</p>
						<img src="http://res.cloudinary.com/lawless/image/upload/c_scale,h_25/v1496319629/bornce_coin_vthk3p.png" alt="insert_coin">
					</div>					
				</div>
				<div class="col-xs-3">
					<div class="container-item">
						<img id="poster-s" class="img-responsive" src="http://res.cloudinary.com/lawless/image/upload/c_scale,h_200,w_125/v1496691060/alien_covenant_u7ygov.jpg" alt="poster">
						<p>Alien Covenant</p>
						<img src="http://res.cloudinary.com/lawless/image/upload/c_scale,h_25/v1496319629/gold_coin_md3n8f.png" alt="insert_coin">
					</div>					
				</div>
				<div class="col-xs-3">
					<div class="container-item">
						<img id="poster-s" class="img-responsive" src="http://res.cloudinary.com/lawless/image/upload/c_scale,h_200,w_125/v1496691060/galaxy1_bvork2.jpg" alt="poster">
						<p>Guardians of the galaxy</p>
						<img src="http://res.cloudinary.com/lawless/image/upload/c_scale,h_25/v1496319629/silver_coin_oq6chf.png" alt="insert_coin">
					</div>					
				</div>				
			</div>
		</div>
		<li class="righty">More ...</li>
		<div class="container-set">
			<h2>RATING HISTORY</h2>
			<div class="row">
				<div class="col-xs-6">
					<div class="container-rate">
						<table>
							<tr>
								<th>
									<img id="poster-s" class="img-responsive" src="http://res.cloudinary.com/lawless/image/upload/c_scale,h_100,w_75/v1496691059/braveheart_fyfxs0.jpg" alt="poster">
								</th>
								<th>								
									<p><b>Braveheart</b>(1995)</p>
									<p>Rating: <b>10</b></p>	
								</th>
							</tr>
						</table>					
					</div>
				</div>
				<div class="col-xs-6">
					<div class="container-rate">
						<table>
							<tr>
								<th>
									<img id="poster-s" class="img-responsive" src="http://res.cloudinary.com/lawless/image/upload/c_scale,h_100,w_75/v1496691061/prometheus_rgkgzj.jpg" alt="poster">
								</th>
								<th>								
									<p><b>Prometheus</b>(1995)</p>
									<p>Rating: <b>7</b></p>	
								</th>
							</tr>
						</table>					
					</div>
				</div>			
			</div>
			<div class="row">
				<div class="col-xs-6">
					<div class="container-rate">
						<table>
							<tr>
								<th>
									<img id="poster-s" class="img-responsive" src="http://res.cloudinary.com/lawless/image/upload/c_scale,h_100,w_75/v1496691060/pcarabiean1_qgwvid.jpg" alt="poster">
								</th>
								<th>
									<p><b>Praites of crabean</b>(2013)</p>
									<p>Rating: 9</b></p>
								</th>
							</tr>
						</table>						
					</div>
				</div>				
			</div>
		</div>
		<li class="righty">More ...</li>
	</div>
</div>
<br>

app/views/settings/new.html.erb
<h2>New Settings</h2>

<% if @setting.errors.any? %>
	<% @setting.errors.full_messages.each do |msg| %>
		<!-- <div class="alert alert-danger"><%= msg %></div> -->
		<p hidden><%= flash[:alert] = msg %></p>
		<%if flash.present?%>
			<div class="row">
			    <div class="col-sm-12 col-md-6 col-md-offset-3" style="padding: 0 0">
			        <%= render partial: "shared/flash_messages_fix", flash: flash %>
			    </div>
			</div>
		<%end%>      	
	<% end %>
<% end %>

<!-- 
<% if @setting.errors.any? %>
	<% @setting.errors.full_messages.each do |msg| %>
		<div class="alert alert-danger"><%= msg %></div>      	
	<% end %>
<% end %>

 -->
<%= form_for(@setting) do |f| %>
	<%= f.label :country %> 
	<div class="field">         	 
    	<%= f.select :country, options_for_country, {}, {:prompt => 'Select One Country',  autofocus: 'true', class: 'form-control'}  %>
	</div>  
	<div class="field">
		<%= f.label :language %>        	 
    	<%= f.select :language, options_for_language, {}, {:prompt => 'Select One Country',  autofocus: 'true', class: 'form-control'}  %>
	</div> 
	<div class="field">
		<%= f.submit "Guardar", class:"btn btn-sm btn-danger white pull-right", style:"margin-top: 15px;" %>
	</div>
<% end %>
<div class="row">
	<div class="col-xs-12">
	  	<label for="name">Personal Information</label>
	  	<p>Edit personal information associated with your Rotten Tomatoes account.</p>
	  	<hr> 
	  	<label for="name">Change or Confirm Email Address</label>
	  	<p>Change or confirm your email address for your Rotten Tomatoes account.</p>
	  	<hr>
	  	<label for="name">Profile Display Name</label>
	  	<p>Edit your public profile display name.</p>
	  	<hr>
	  	<label for="name">Profile Details</label>
	  	<p>Edit public profile information about yourself.</p>
	  	<hr> 
	  	<label for="name">Email Preferences</label>
	  	<p>Modify your email subscription settings.</p>
	  	<hr>
	  	<label for="name">Password</label>
	  	<p>Change the password for your Rotten Tomatoes account.</p>
	  	<hr>
	  	<label for="name">Privacy Settings</label>
	  	<p>Manage your profile visibility and share settings.</p>
	  	<hr>
	  	<label for="name">Change Country</label>
	  	<p>Manage your localization setting.</p>
	  	<hr>
	  	<label for="name">Delete Account</label>
	  	<p>Terminate your Rotten Tomatoes account and disconnect from any attached social networks.</p>
	  	<hr>
	</div>
</div>